# Generated by Django 3.2.4 on 2021-07-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=10)),
                ('cantidad', models.IntegerField()),
                ('fecha_disponible', models.DateTimeField()),
                ('disponbile_para_uso', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoBodega',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=10)),
                ('almacen', models.CharField(max_length=15)),
                ('fecha_vencimiento', models.DateTimeField()),
                ('oc_reservada', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoDespachado',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=10)),
                ('cliente', models.CharField(max_length=20)),
                ('oc_cliente', models.CharField(max_length=25)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RecievedOC',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('cliente', models.TextField()),
                ('proveedor', models.TextField()),
                ('sku', models.IntegerField()),
                ('fecha_entrega', models.DateTimeField()),
                ('cantidad', models.IntegerField()),
                ('cantidad_despachada', models.IntegerField(default=0)),
                ('precio_unitario', models.IntegerField()),
                ('canal', models.CharField(max_length=3)),
                ('estado', models.CharField(max_length=10)),
                ('notas', models.TextField(blank=True)),
                ('rechazo', models.TextField(blank=True)),
                ('anulacion', models.TextField(blank=True)),
                ('url_notification', models.TextField(blank=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SentOC',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('cliente', models.TextField()),
                ('proveedor', models.TextField()),
                ('sku', models.IntegerField()),
                ('fecha_entrega', models.DateTimeField()),
                ('cantidad', models.IntegerField()),
                ('cantidad_despachada', models.IntegerField(default=0)),
                ('precio_unitario', models.IntegerField()),
                ('canal', models.CharField(max_length=3)),
                ('estado', models.CharField(max_length=10)),
                ('notas', models.TextField(blank=True)),
                ('rechazo', models.TextField(blank=True)),
                ('anulacion', models.TextField(blank=True)),
                ('url_notification', models.TextField(blank=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
