# Generated by Django 3.2.4 on 2021-07-05 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_productodespachado_cliente'),
        ('api', '0002_auto_20210704_2017'),
    ]

    operations = [
    ]
