# Generated by Django 3.2.4 on 2021-07-01 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210621_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algunmodelo',
            name='id',
            field=models.CharField(editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
