# Generated by Django 3.2.4 on 2021-06-26 22:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210621_0325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('sku_numlote', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=10)),
                ('fecha_vencimiento', models.DateTimeField()),
                ('cantidad_disponible', models.IntegerField()),
                ('productos', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), size=None)),
            ],
        ),
    ]
