# Generated by Django 3.2.4 on 2021-07-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_productodespachado_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='sku',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='productobodega',
            name='almacen',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productobodega',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productobodega',
            name='sku',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='productodespachado',
            name='cliente',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='productodespachado',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productodespachado',
            name='oc_cliente',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='productodespachado',
            name='sku',
            field=models.CharField(max_length=15),
        ),
    ]
