# Generated by Django 3.2.4 on 2021-07-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_merge_20210705_0314'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbassyOC',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('cliente', models.TextField()),
                ('proveedor', models.TextField()),
                ('sku', models.IntegerField()),
                ('fecha_entrega', models.DateTimeField()),
                ('cantidad', models.IntegerField()),
                ('cantidad_despachada', models.IntegerField(default=0)),
                ('precio_unitario', models.IntegerField()),
                ('canal', models.CharField(max_length=3)),
                ('estado', models.CharField(max_length=10)),
                ('notas', models.TextField(blank=True)),
                ('rechazo', models.TextField(blank=True)),
                ('anulacion', models.TextField(blank=True)),
                ('url_notification', models.TextField(blank=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='disponbile_para_uso',
            new_name='disponible_para_uso',
        ),
        migrations.AlterField(
            model_name='productobodega',
            name='oc_reservada',
            field=models.TextField(default=''),
        ),
    ]
