# Generated by Django 3.2.4 on 2021-07-05 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210704_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='disponbile_para_uso',
            new_name='disponible_para_uso',
        ),
    ]
