# Generated by Django 3.2.4 on 2021-06-27 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_lote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=10)),
                ('cantidad', models.IntegerField()),
                ('fecha_disponible', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductoDespachado',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=10)),
                ('cliente', models.CharField(max_length=20)),
                ('oc_cliente', models.CharField(max_length=25)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductoBodega',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=10)),
                ('almacen', models.CharField(max_length=15)),
                ('fecha_vencimiento', models.DateTimeField()),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.lote')),
            ],
        ),
    ]
