# Generated by Django 3.2.4 on 2021-07-06 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_merge_20210705_0314'),
        ('api', '0004_rename_disponbile_para_uso_pedido_disponible_para_uso'),
    ]

    operations = [
    ]
