# Generated by Django 3.2.4 on 2021-07-04 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_algunmodelo_id'),
        ('api', '0004_pedido_productobodega_productodespachado'),
    ]

    operations = [
    ]
