# Generated by Django 3.2.4 on 2021-07-04 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_merge_20210704_0058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='AlgunModelo',
        ),
        migrations.RenameField(
            model_name='recievedoc',
            old_name='url_notificaion',
            new_name='url_notification',
        ),
        migrations.RenameField(
            model_name='sentoc',
            old_name='url_notificaion',
            new_name='url_notification',
        ),
        migrations.RemoveField(
            model_name='productobodega',
            name='lote',
        ),
        migrations.AddField(
            model_name='pedido',
            name='disponbile_para_uso',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productobodega',
            name='oc_reservada',
            field=models.TextField(default=None),
        ),
        migrations.DeleteModel(
            name='Lote',
        ),
    ]
