# Generated by Django 3.2.4 on 2021-07-18 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210717_1701'),
        ('api', '0005_merge_20210706_1600'),
    ]

    operations = [
    ]
